<?php
/** op-app-skeleton-2020-nep:/asset/bootstrap/app/config-admin.phtml
 *
 * @created   2020-07-24
 * @version   1.0
 * @package   op-app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<!doctype html>
<html>
	<head>
		<style>
		div.pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
			font-family: monospace;
			font-size: 16px;
		}

		.margin.left {
			margin-left: 1em;
		}
		</style>
	</head>
	<body>
		<section>
			<h1>The admin config file has not been set.</h1>

			<p class="margin left">File path is</p>
			<div class="pre margin left">asset/config/admin.php</div>

			<p class="margin left">Description is</p>
			<div class="pre margin left">
				&lt;?php<br/>
				return [<br/>
				<div class="margin left">
				  OP\Env::_ADMIN_IP_   => '127.0.0.1',<br/>
				  OP\Env::_ADMIN_MAIL_ => 'to_address@example.com',<br/>
				  OP\Env::_MAIL_FROM_  => 'from_address@example.com'<br/>
				</div>
				];<br/>
				// ?&gt;
			</div>
		</section>
	</body>
</html>
<?php
exit();
