<?php
/** op-module-bootstrap:/app/gitsubmodule.phtml
 *
 * @created   2020-07-13
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

//	AppRoot is uncertain.
$app_root = rtrim($_SERVER['DOCUMENT_ROOT'], '/').$_SERVER['REQUEST_URI'];

?>
<!doctype html>
<html>
	<head>
		<style>
		div.pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
			font-family: monospace;
			font-size: 16px;
		}
		</style>
	</head>
	<body>
		<section>
			<h1>Not initializing git submodule</h1>
			<p>Execute the following command.</p>
			<div class="pre">
				cd <?= $app_root ?><br/>
				git checkout 2021<br/>
				sh asset/git/submodule/init.sh
			</div>
		</section>
	</body>
</html>
<?php
exit();
