<?php
/** op-app-skeleton-2020-nep:/asset/template/welcome.phtml
 *
 * @created   2017-07-28
 * @version   1.0
 * @package   op-app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-22
 */
namespace OP;

/** use
 *
 * @created   2019-12-09
 */
use function OP\APP\FUNC\GetLinkList;

//	...
Unit('App')->Title('Welcome');

//	...
$path   = ConvertPath('app:/_develop/', false);
$exists = file_exists($path);

?>
<style>
#welcome img {
	float: left;
	width: 10em;
	margin-right:  1em;
	margin-bottom: 1em;
}
</style>
<section id="welcome" data-i18n="true" data-i18n-locale="en:us">
	<!-- Introduction -->
	<h2>Welcome to the "onepiece-framework"!!</h2>
	<img src="<?= ConvertURL('app:/img/icon.png') ?>" />
	<p>
		Congratulations!
		onepiece-framework did booted!!
		How was it? Have you boot easily? So, The onepiece-framework is insanely great!!
		Because, the onepiece-framework is everything is intuitive.
	</p>
	<h3>The "NEW WORLD" is a new world.</h3>
	<p>
		For example, you can easily find the file of endpoint.
		Please try to find the running file from the URL of this page.
		It should be easy to find.
		Was it intuitive?
		You found it right away, right?
		This mechanism we so call "NEW WORLD".
		The "NEW WORLD" is a new world.
		Please enjoy this non stress and comfortable world.
	</p>

	<!-- Feature -->
	<section class="float left">
		<h3>Feature</h3>
		<ul>
			<li><a href="html_pass_through.html">Html pass through</a></li>
		</ul>
	</section>
	<br class="float clear both"/>
</section>

<!-- Separator -->
<hr class="float clear both"/>

<?php if( $exists ): ?>

<!-- Already linked -->
<section>
	<h2>Built-in Service</h2>
	<ul>
		<li><a href="_develop">develop</a></li>
	</ul>
</section>

<?php else: ?>

<!-- Not linked yet -->
<section>
	<h2>Example</h2>
	<div class="pre code">
cd <?= ConvertPath('app:/') ?><br/>
ln -s asset/develop _develop
	</div>
</section>

<?php endif; ?>
