<?php
/** op-app-skeleton-2020-nep:/asset/template/layout/footer.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   op-app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-04-03
 */
namespace OP;

//	...
$config = Config::Get('app');

//	...
if( $analytics = $config['analytics'] ?? null ){
	Template('analytics/action.php',['analytics'=>$analytics]);
}

?>
<footer>
	<?= $config['copyright'] ?? null ?>
</footer>
