<?php
/** op-app-skeleton-2020-nep:/asset/template/layout/header.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   op-app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-03-01
 */
namespace OP;

?>
<header>
	<a href="<?= ConvertURL('app:/') ?>"><?= Config::Get('app')['title'] ?? 'TOP' ?></a>
</header>
